name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  json_annotation:
  flutter_riverpod:
  http:
  equatable:
  shared_preferences:
  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail:
  coverage: ^1.0.3
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
